#!/bin/bash
rule download:
	shell:'mkdir sraFiles ; list="SRR628582 SRR628583"; for i in $list do wget -O sraFiles/$i.sra; https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos1/sra-pub-run-5/$i/$i.1 -0 sraFiles/'
