#!/bin/bash

rule all:
	input:
		"essai.fastq"
rule makefastq:
	output:
		"essai.fastq"
	singularity : 
		"docker://evolbioinfo/sratoolkit:v2.5.7"
	shell:
		'vdb-config -i'
		'fastq-dump --split-files SRR628582'
